max_width = 80
# newline_style = "Unix"
# use_field_init_shorthand = true
# use_try_shorthand = true
# format_strings = true
# group_imports = "One"
# format_code_in_doc_comments = true
# imports_granularity = "Crate"
