[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"

[watch]
watch = ["./index.html", "src/", "style/"]
ignore = []

[serve]
addr = "127.0.0.1"
port = 8080
open = false
no_autoreload = false

[clean]
dist = "dist"
cargo = true

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = [
    "tailwindcss",
    "-i",
    "style.css",
    "-o",
    "style/style.min.css",
    "--minify",
]
